version: '3.9'

services:
  db:
    image: postgres:16-alpine3.19
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
    volumes:
      - psql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  psql-data:
